---@module 'sandbox.@types'
--- Shared type annotations for sandbox.nvim.

---@alias Sandbox.Engine "podman"|"docker"|"nerdctl"

---@class Sandbox.Config.Options
---@field engine Sandbox.Engine|nil
---@field confirm_destructive boolean|nil ask before remove/prune/kill (default true)
---@field default_shell string|nil shell used by `container exec` when none is given (default "sh")
---@field refresh_interval integer|nil ms between auto-refreshes of list views; nil/0 disables (default nil)
---@field list_split "above"|"below"|"left"|"right"|nil window placement for list views (default "left")
---@field list_size integer|nil width/height of list view splits; nil uses Neovim's default
---@field progress_style "auto"|"notify"|"statusline"|"fidget"|"float"|"kit"|nil
--- indicator for long-running argv (pull/push/build); needs lib.nvim, no-op without it (default "auto")
--- How much of an unrecognized adapter error reaches the notification
--- (default 200). The full text always goes to sandbox.logger, and a
--- truncated message says where to read it.
---@field max_error_length integer|nil
---@field status_cache_ttl_ms integer|nil how long a statusline reading stays fresh, in ms (default 3000)
---@field completion_cache_ttl_ms integer|nil how long a completion listing stays cached, in ms (default 4000)
---@field menu Sandbox.MenuOptions|nil
---@field keymaps Sandbox.Keymaps|false|nil list-view keymap overrides (default: nil, all defaults)

--- Per-list keymap overrides. Each field is a table of `action = lhs`, where
--- an lhs may be one key, a list of keys, or `false` to drop that action; a
--- whole list kind may be `false` to drop all of its keys.
---
--- Action names come from the descriptions the list views declare, slugified:
--- "logs (follow)" is `logs_follow`. A name that matches nothing is reported
--- rather than silently ignored, so `:messages` says what went wrong.
---@class Sandbox.Keymaps
--- The four keys every list shares: `close` (`q`), `engine` (`E`),
--- `filter` (`f`), `help` (`?`).
---@field list? table<string, string|string[]|false>|false
--- e.g. `inspect` (`<CR>` and `i`), `remove` (`D`), `refresh_list` (`R`).
---@field containers? table<string, string|string[]|false>|false
---@field containers_visual? table<string, string|string[]|false>|false bulk actions on a Visual selection
---@field images? table<string, string|string[]|false>|false
---@field images_visual? table<string, string|string[]|false>|false
---@field volumes? table<string, string|string[]|false>|false
---@field volumes_visual? table<string, string|string[]|false>|false
---@field networks? table<string, string|string[]|false>|false
---@field networks_visual? table<string, string|string[]|false>|false
--- The single `close` key of the inspect / log-follow scratch views.
---@field inspect? table<string, string|string[]|false>|false
---@field logs? table<string, string|string[]|false>|false

---Opt-out for the list-view right-click context menu
---(sandbox.integrations.menu, lib.nvim.contextmenu). sandbox.nvim ships no
---nvzone/menu dependency itself; this only gates whether the trigger is
---bound and whether entries are returned.
---@class Sandbox.MenuOptions
---@field enable boolean|nil provide the right-click context menu on list-view buffers (default true)

---@class Sandbox.RunOpts
---@field image string
---@field name? string
---@field ports? string[] "host:container" mappings
---@field volumes? string[] "host:container" mount specs
---@field env? string[] "KEY=VALUE" entries
---@field command? string[] overrides the image's default CMD/entrypoint args
